# Generated by Django 3.1.7 on 2021-03-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='', max_length=100, verbose_name='Product Name')),
                ('Item_Code', models.CharField(default='', max_length=100, verbose_name='Item Code')),
                ('Quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('Rate', models.IntegerField(default=0, verbose_name='Rate')),
            ],
        ),
    ]
