# Generated by Django 3.1.7 on 2021-03-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(default='', max_length=100, verbose_name='Username')),
                ('Password', models.CharField(default='', max_length=100, verbose_name='Password')),
            ],
        ),
    ]
