# Generated by Django 3.1.7 on 2021-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='C_Pro_Name',
            field=models.CharField(default='', max_length=100, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='bill',
            name='C_Quant',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
